version: '3.8'

services: 
  web:
    build:
      context: .
      dockerfile: Containerfile
    restart: always
    env_file:
      - .env
    depends_on:
      s3proxy:
        condition: service_healthy
      db:
        condition: service_healthy
      azurite:
        condition: service_healthy
    ports:
      - ${WEB_EXTERNAL_PORT}:${WEB_INTERNAL_PORT}
